// vue-homework/vue-mental-arithmetic/src/views/Menu.vue
<template>
    <div id="menu">
                
                <h1>Привет!</h1>
                <p>Добро пожаловать на {{dayOfTraining}} тренировочный день</p>
                <p>Ваш последний результат - решено {{lastQuantityСompletedTasks}} из {{lastQuantityTasks}}.</p>
                <p>Общая точность {{overallAccuracy}}%</p>

                <div>
                    <p>Настройки</p>
                    
                    <div class="demo">
                        <div class="range-slider">
                            <input type="range" v-model="duration" @input='changeDuration' min="1" max="15" range="true"/>
                            <span class="range-value">{{duration}}</span>
                        </div>
                        <p id="durationValue">Длительность {{duration}} минут</p>
                    </div>

                    <div class="demo2">
                        <input type="range" v-model="complexity" @input='changeСomplexity' range="true" min="1" max="10"/>
                        <p id="complexity">Сложность {{complexity}}</p>
                    </div>

                    <ArithmeticOperationTypeList 
                        v-bind:arithmeticOperationTypes="arithmeticOperationTypes"
                        @change-value="changeValue" />

                </div>

                <button>
                    <router-link :to="{ name: 'game', params: 
                            { 
                                dayOfTraining,
                                lastQuantityСompletedTasks,
                                lastQuantityTasks,
                                overallAccuracy,
                                duration,
                                complexity,
                                sum: arithmeticOperationTypes.filter((type)=>type.id==='sum')[0].value,
                                diff: arithmeticOperationTypes.filter((type)=>type.id==='diff')[0].value,
                                multi: arithmeticOperationTypes.filter((type)=>type.id==='multi')[0].value,
                                div: arithmeticOperationTypes.filter((type)=>type.id==='div')[0].value,
                                expon: arithmeticOperationTypes.filter((type)=>type.id==='expon'[0]).value
                            }
                        }">Play!</router-link>
                </button>
            
            </div>
</template>

<script>
    import ArithmeticOperationTypeList from '@/components/ArithmeticOperationTypeList'
    
    export default {
        data() { 
            return {
                dayOfTraining: 1,
                lastQuantityСompletedTasks: 0,
                lastQuantityTasks: 0,
                overallAccuracy: 100,
                duration: 1,
                complexity: 1,
                arithmeticOperationTypes: [
                    {
                        id: "sum",
                        type: "summation",
                        value: false,
                        discription: "Суммирование"
                    },
                    {
                        id: "diff",
                        type: "difference",
                        value: false,
                        discription: "Разность"
                    },
                    {
                        id: "multi",
                        type: "multiplication",
                        value: false,
                        discription: "Умножение"
                    },
                    {
                        id: "div",
                        type: "division",
                        value: false,
                        discription: "Деление"
                    },
                    {
                        id: "expon",
                        type: "exponentiation",
                        value: false,
                        discription: "Возведение в степень"
                    }
                ]
            }
        },
        mounted() {
            this.dayOfTraining = localStorage.dayOfTraining ? localStorage.dayOfTraining : 1;
            this.lastQuantityСompletedTasks = localStorage.lastQuantityСompletedTasks ? localStorage.lastQuantityСompletedTasks : 0;
            this.lastQuantityTasks = localStorage.lastQuantityTasks ? localStorage.lastQuantityTasks : 0;
            this.overallAccuracy = localStorage.overallAccuracy ? localStorage.overallAccuracy : 100;
        },
        methods: {
            changeСomplexity: function(e) {
                this.complexity = e.currentTarget.value
            },
            changeDuration: function(e) {
                this.duration = e.currentTarget.value
            },
            changeValue(id) {
                const type = this.arithmeticOperationTypes.filter((type)=>type.id===id)[0];
                type.value = !type.value;
            }
            
        },
        
        components: {
            ArithmeticOperationTypeList
        }
    }
</script>

// react-mental-arithmetic/src/js/components/Menu.jsx
import React from 'react';
import {Link} from 'react-router-dom';

class Menu extends React.Component{

    constructor(props) {
        super(props);
        this.state = {
            dayOfRegistration:  new Date('12-09-2019'),
            duration: 1,
            complexity: 1
        };

        this.changeDuration = this.changeDuration.bind(this);
        this.changeСomplexity = this.changeСomplexity.bind(this);
    }

    changeDuration(e) {
        this.setState({
            duration: e.currentTarget.value
        });
    }

    changeСomplexity(e) {
        this.setState({
            complexity: e.currentTarget.value
        });
    }

    render() {
        let daysCount = Math.ceil(Math.abs( new Date().getTime() - this.state.dayOfRegistration.getTime()) / (1000 * 3600 * 24));
        let duration = this.state.duration;
        let complexity = this.state.complexity;

        return (
            <div className="menu">
                
                <h1>Привет!</h1>
                <p>Добро пожаловать на {daysCount} тренировочный день</p>
                <p>Ваш последний результат - решено {} из {}.</p>
                <p>Общая точность {}%</p>

                <div>
                    <p>Настройки</p>
                    
                    
                    {/* <input type="range" id="r1" min="1" max="15" value={duration} onInput={this.changeDuration}/> */}
                    
                    <div className="demo">
                        <div className="range-slider">
                            <input type="range" value={duration} onInput={this.changeDuration} min="1" max="15" range="true"/>
                            <span className="range-value">{duration}</span>
                        </div>
                        <p id="durationValue">Длительность {duration} минут</p>
                    </div>


                    <input type="range" id="r2" min="1" max="10" value={complexity} onInput={this.changeСomplexity}/>
                    <p id="complexity">Сложность {complexity}</p>

                    <div>
                        <p>
                            <input type="checkbox" id="sum" name="sum" value="summation"/>
                            <label for="sum">Суммирование</label>
                        </p>
                        <p>
                            <input type="checkbox" id="diff" name="diff" value="difference"/>
                            <label for="diff">Разность</label>
                        </p>
                        <p>
                            <input type="checkbox" id="multi" name="multi" value="multiplication"/>
                            <label for="multi">Умножение</label>
                        </p>
                        <p>
                            <input type="checkbox" id="div" name="div" value="division"/>
                            <label for="div">Деление</label>  
                        </p>
                        <p>
                            <input type="checkbox" id="expon" name="expon" value="exponentiation"/>
                            <label for="expon">Возведение в степень</label>
                        </p>
                    </div>
                </div>

                <button >
                    <Link to='/game' >Play!</Link>
                </button>
            </div>
        );
    }

}  

export default Menu;
